version: '3.8'
services:
  nanote:
    image: omarmir/nanote:latest
    ports:
      - '3030:3000'
    #environment:
    #  - NOTES_PATH=/notes
    #  - SECRET_KEY=<yourkey>
    #volumes:
    #  - /path/to/local/folder:/notes
